### ISSUE TITLE
Yay

### ISSUE THREAD

**Issue by FocuzJS** [nlepleux/blanket#1]
Can't wait for KPP in 2009 to mitigate this.. What's wrong you couldn't make money off this yourself 😂

**Comment by nlepleux** [comment]
I have plenty of other ways to make money.
Thanks for the heads up!

**Comment by FocuzJS** [comment]
What a waste of a good native method. Not to even mention the countless people you just silently fucked over. Did you even see how brain-dead the guy you were replying to is... Quite disrespectful to the community if you ask me.. You basically uncover a 0day (i bet it was hard with symbols 😒) and can't wait to share it on UC so much so that you reply to a guy who doesn't even know what manual map driver means 😂 
Pretty Pathetic, enjoy getting your dick sucked by the pasters I guess since that's what it seems you want 😄
